### ISSUE TITLE
Crawl all comments of a specific post

### ISSUE THREAD

**Issue by Aleyasen** [nacimgoura/instagram-profilecrawl#14]
Does the package support crawling all the comments of a post?

**Comment by nacimgoura** [comment]
Hello @Aleyasen. I thought about putting it in place but the problem is that there can be thousands of comments for a post. At the beginning 10 are displayed, and you have to press the button to display 10 others and so on.  But the problem (apart from the time it will take) is that instagram will block the loading of comments after several loads. So for these reasons this crawl does not retrieve comments from posts.
